name: flutter_api_movies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive_ce: ^2.11.3
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  redux: ^5.0.0
  redux_epics: ^0.15.2
  retrofit: ^4.6.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/images/svg/
    - assets/lotties/
